'use client'

import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { CalendarClock, ClipboardCheck, Paperclip, Plus, RefreshCw, Wrench } from 'lucide-react'
import { assignWorkOrder, createMaintenanceSchedule, createMaintenanceVendor, createWorkOrder, getWorkOrderWorkspace, linkExpenseToWorkOrder, updateWorkOrderStatus } from '@/app/actions/work-orders'

const initialForm = { title: '', description: '', category: 'GENERAL', priority: 'MEDIUM', assignedToId: '', leaseId: '', vendorId: '', dueAt: '', estimatedCost: 0 }

export default function MaintenanceClient() {
  const [data, setData] = useState<any>({ orders: [], staff: [], leases: [], vendors: [], schedules: [] })
  const [message, setMessage] = useState('')
  const [form, setForm] = useState<any>(initialForm)
  const [files, setFiles] = useState<File[]>([])
  const [expenseForm, setExpenseForm] = useState({ expenseId: '', workOrderId: '' })
  const [vendorForm, setVendorForm] = useState({ name: '', phone: '', email: '' })
  const [scheduleForm, setScheduleForm] = useState({ title: '', leaseId: '', vendorId: '', assignedToId: '', frequency: 'MONTHLY', nextDueAt: '', priority: 'MEDIUM', category: 'GENERAL', estimatedCost: 0 })

  const load = useCallback(async () => {
    const result = await getWorkOrderWorkspace()
    if (result.success) setData(result.data)
  }, [])
  // Initial data hydration is an intentional async server-action boundary.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load() }, [load])

  async function uploadFiles() {
    if (files.length === 0) return [] as string[]
    const body = new FormData()
    for (const file of files) body.append('files', file)
    body.append('folder', 'maintenance')
    const response = await fetch('/api/upload', { method: 'POST', body })
    const result = await response.json() as { urls?: string[]; error?: string }
    if (!response.ok) throw new Error(result.error ?? 'Could not upload attachments')
    return result.urls ?? []
  }

  async function submit(event: FormEvent) {
    event.preventDefault(); setMessage('')
    try {
      const attachments = await uploadFiles()
      const result = await createWorkOrder({ ...form, assignedToId: form.assignedToId ? Number(form.assignedToId) : null, leaseId: form.leaseId ? Number(form.leaseId) : null, vendorId: form.vendorId ? Number(form.vendorId) : null, estimatedCost: Number(form.estimatedCost), attachments })
      setMessage(result.success ? 'Work order created.' : result.error ?? 'Could not create work order')
      if (result.success) { setForm(initialForm); setFiles([]); await load() }
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not upload attachments') }
  }

  async function status(id: number, next: string) { const result = await updateWorkOrderStatus({ id, status: next }); setMessage(result.success ? 'Work order updated.' : result.error ?? 'Could not update work order'); await load() }
  async function assign(id: number, staffId: string) { const result = await assignWorkOrder(id, staffId ? Number(staffId) : null); setMessage(result.success ? 'Assignment updated.' : result.error ?? 'Could not assign work order'); await load() }
  async function linkExpense(event: FormEvent) { event.preventDefault(); const result = await linkExpenseToWorkOrder(Number(expenseForm.expenseId), Number(expenseForm.workOrderId)); setMessage(result.success ? 'Expense linked and actual cost recalculated.' : result.error ?? 'Could not link expense'); if (result.success) setExpenseForm({ expenseId: '', workOrderId: '' }); await load() }
  async function addVendor(event: FormEvent) { event.preventDefault(); const result = await createMaintenanceVendor(vendorForm); setMessage(result.success ? 'Maintenance vendor added.' : result.error ?? 'Could not add vendor'); if (result.success) { setVendorForm({ name: '', phone: '', email: '' }); await load() } }
  async function addSchedule(event: FormEvent) { event.preventDefault(); const result = await createMaintenanceSchedule({ ...scheduleForm, leaseId: scheduleForm.leaseId ? Number(scheduleForm.leaseId) : null, vendorId: scheduleForm.vendorId ? Number(scheduleForm.vendorId) : null, assignedToId: scheduleForm.assignedToId ? Number(scheduleForm.assignedToId) : null, estimatedCost: Number(scheduleForm.estimatedCost) }); setMessage(result.success ? 'Preventive schedule created.' : result.error ?? 'Could not create schedule'); if (result.success) { setScheduleForm({ ...scheduleForm, title: '', nextDueAt: '' }); await load() } }

  return <main className="p-4 md:p-8 space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.2em] text-indigo-500">Facilities operations</p><h1 className="mt-1 text-3xl font-semibold">Maintenance Work Orders</h1><p className="mt-2 text-sm text-muted">Schedule, assign, evidence and cost repairs across managed leases and bookings. Priority defaults to the Dubai operations SLA.</p></div><button onClick={load} className="rounded-lg border border-border p-2" aria-label="Refresh maintenance"><RefreshCw className="h-4 w-4" /></button></div>
    {message && <div className="rounded-lg border border-indigo-200 bg-indigo-50 px-4 py-3 text-sm text-indigo-800">{message}</div>}
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(0,1.3fr)]">
      <form onSubmit={submit} className="rounded-xl border border-border bg-card p-5 space-y-3"><h2 className="flex items-center gap-2 font-semibold"><Plus className="h-5 w-5 text-indigo-500" /> New work order</h2><input required placeholder="Issue title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className="field" /><textarea placeholder="Description / access notes" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="field min-h-24" /><div className="grid gap-3 sm:grid-cols-2"><select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} className="field"><option value="GENERAL">General</option><option value="PLUMBING">Plumbing</option><option value="ELECTRICAL">Electrical</option><option value="HVAC">HVAC</option><option value="CIVIL">Civil</option><option value="CLEANING">Cleaning</option></select><select value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value })} className="field"><option value="LOW">Low · 7 days</option><option value="MEDIUM">Medium · 3 days</option><option value="HIGH">High · 24 hours</option><option value="URGENT">Urgent · 4 hours</option></select><select value={form.assignedToId} onChange={e => setForm({ ...form, assignedToId: e.target.value })} className="field"><option value="">Assign staff</option>{data.staff.map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={form.leaseId} onChange={e => setForm({ ...form, leaseId: e.target.value })} className="field"><option value="">Lease (optional)</option>{data.leases.map((item: any) => <option key={item.id} value={item.id}>{item.contractNumber} · {item.contact.name}</option>)}</select><select value={form.vendorId} onChange={e => setForm({ ...form, vendorId: e.target.value })} className="field"><option value="">Vendor (optional)</option>{data.vendors.map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input type="datetime-local" value={form.dueAt} onChange={e => setForm({ ...form, dueAt: e.target.value })} className="field" /><input type="number" min="0" placeholder="Estimated cost (AED)" value={form.estimatedCost} onChange={e => setForm({ ...form, estimatedCost: e.target.value })} className="field" /><label className="flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm text-muted"><Paperclip className="h-4 w-4" /><span>Before / reference files</span><input type="file" multiple accept="image/*,application/pdf" onChange={e => setFiles(Array.from(e.target.files ?? []).slice(0, 5))} className="min-w-0 text-xs" /></label></div><p className="text-xs text-muted">Leave due date blank to apply the priority SLA automatically. Up to five evidence files are stored with the work order.</p><button className="w-full rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-medium text-white">Create work order</button></form>
      <div className="space-y-6"><form onSubmit={addVendor} className="rounded-xl border border-border bg-card p-5 space-y-3"><h2 className="font-semibold">Maintenance vendor</h2><div className="grid gap-3 sm:grid-cols-3"><input required placeholder="Company name" value={vendorForm.name} onChange={e => setVendorForm({ ...vendorForm, name: e.target.value })} className="field" /><input placeholder="Phone" value={vendorForm.phone} onChange={e => setVendorForm({ ...vendorForm, phone: e.target.value })} className="field" /><input type="email" placeholder="Email" value={vendorForm.email} onChange={e => setVendorForm({ ...vendorForm, email: e.target.value })} className="field" /></div><button className="rounded-lg border border-border px-4 py-2.5 text-sm">Add vendor</button></form><form onSubmit={linkExpense} className="rounded-xl border border-border bg-card p-5 space-y-3"><h2 className="font-semibold">Link expense to work</h2><p className="text-sm text-muted">Actual cost is recalculated from linked approved expenses.</p><div className="grid gap-3 sm:grid-cols-2"><input required type="number" min="1" placeholder="Expense ID" value={expenseForm.expenseId} onChange={e => setExpenseForm({ ...expenseForm, expenseId: e.target.value })} className="field" /><select required value={expenseForm.workOrderId} onChange={e => setExpenseForm({ ...expenseForm, workOrderId: e.target.value })} className="field"><option value="">Select work order</option>{data.orders.map((item: any) => <option key={item.id} value={item.id}>{item.displayId} · {item.title}</option>)}</select></div><button className="rounded-lg border border-border px-4 py-2.5 text-sm">Link and recalculate</button></form></div>
    </section>
    <section className="rounded-xl border border-border bg-card p-5"><div className="mb-4 flex items-center gap-2"><CalendarClock className="h-5 w-5 text-indigo-500" /><h2 className="font-semibold">Preventive maintenance schedule</h2></div><form onSubmit={addSchedule} className="grid gap-3 md:grid-cols-4"><input required placeholder="Schedule title" value={scheduleForm.title} onChange={e => setScheduleForm({ ...scheduleForm, title: e.target.value })} className="field" /><select value={scheduleForm.frequency} onChange={e => setScheduleForm({ ...scheduleForm, frequency: e.target.value })} className="field"><option>WEEKLY</option><option>MONTHLY</option><option>QUARTERLY</option><option>SEMI_ANNUAL</option><option>ANNUAL</option></select><input required type="datetime-local" value={scheduleForm.nextDueAt} onChange={e => setScheduleForm({ ...scheduleForm, nextDueAt: e.target.value })} className="field" /><select value={scheduleForm.leaseId} onChange={e => setScheduleForm({ ...scheduleForm, leaseId: e.target.value })} className="field"><option value="">Lease (optional)</option>{data.leases.map((item: any) => <option key={item.id} value={item.id}>{item.contractNumber}</option>)}</select><select value={scheduleForm.vendorId} onChange={e => setScheduleForm({ ...scheduleForm, vendorId: e.target.value })} className="field"><option value="">Vendor (optional)</option>{data.vendors.map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={scheduleForm.assignedToId} onChange={e => setScheduleForm({ ...scheduleForm, assignedToId: e.target.value })} className="field"><option value="">Assign staff</option>{data.staff.map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-medium text-white">Create recurring schedule</button></form><div className="mt-4 flex flex-wrap gap-2 text-xs text-muted">{data.schedules.map((item: any) => <span key={item.id} className="rounded-full bg-muted/10 px-3 py-1">{item.title} · {item.frequency} · next {new Date(item.nextDueAt).toLocaleDateString()}</span>)}</div></section>
    <section className="rounded-xl border border-border bg-card p-5"><div className="mb-4 flex items-center gap-2"><Wrench className="h-5 w-5 text-indigo-500" /><h2 className="font-semibold">Work-order register</h2></div><div className="space-y-3">{data.orders.map((order: any) => <article key={order.id} className="rounded-lg border border-border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{order.displayId}</span><span className="rounded-full bg-muted/15 px-2 py-1 text-xs">{order.priority}</span><span className={`rounded-full px-2 py-1 text-xs ${order.dueAt && new Date(order.dueAt) < new Date() && !['COMPLETED', 'CANCELLED'].includes(order.status) ? 'bg-red-100 text-red-700' : 'bg-indigo-50 text-indigo-700'}`}>{order.status}</span></div><p className="mt-2 text-sm">{order.title} · {order.category}</p><p className="mt-1 text-xs text-muted">{order.leaseNumber ? `Lease ${order.leaseNumber}` : 'General maintenance'} · Due {order.dueAt ? new Date(order.dueAt).toLocaleString() : '—'} · Estimated AED {order.estimatedCost.toLocaleString()} · Actual AED {order.actualCost.toLocaleString()}</p><p className="mt-1 text-xs text-muted">{order.vendor?.name ? `Vendor: ${order.vendor.name}` : 'No vendor'} · {order.attachments.length} attachment(s)</p></div><div className="flex flex-wrap gap-2"><select value={order.assignedToId ?? ''} onChange={e => assign(order.id, e.target.value)} className="field min-w-[150px]"><option value="">Unassigned</option>{data.staff.map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={order.status} onChange={e => status(order.id, e.target.value)} className="field min-w-[140px]"><option value="OPEN">Open</option><option value="SCHEDULED">Scheduled</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option><option value="CANCELLED">Cancelled</option></select></div></div></article>)}{data.orders.length === 0 && <div className="py-8 text-center text-sm text-muted"><ClipboardCheck className="mx-auto mb-2 h-8 w-8" />No work orders yet.</div>}</div></section>
  </main>
}
